
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const ADD_COMMENT = 'ADD_COMMENT';
export const SET_IS_COMMENT_MODAL_OPEN = 'SET_IS_COMMENT_MODAL_OPEN';
export const SET_SELECTED_COMMENT = 'SET_SELECTED_COMMENT';