
export const ADD_POSTS = 'ADD_POSTS';
export const ADD_POST = 'ADD_POST';
export const REMOVE_POST = 'REMOVE_POST';

export const SET_CURRENT_POST = 'SET_CURRENT_POST';
export const REMOVE_CURRENT_POST = 'REMOVE_CURRENT_POST';

export const SAVE = 'SAVE';
export const ADD_SAVED_POSTS = 'ADD_SAVED_POSTS';
export const REMOVE_SAVED_POST = 'REMOVE_SAVED_POST';
export const REMOVE_SAVED_POSTS = 'REMOVE_SAVED_POSTS';

export const ADD_LIKED_POSTS = 'ADD_LIKED_POSTS';
export const REMOVE_LIKED_POST = 'REMOVE_LIKED_POST';

export const ADD_FEED_POSTS = 'ADD_FEED_POSTS';
export const REMOVE_FEED_POST = 'REMOVE_FEED_POST';

export const ADD_ARCHIVE_POSTS = 'ADD_ARCHIVE_POSTS';
export const REMOVE_ARCHIVE_POST = 'REMOVE_ARCHIVE_POST';

export const UPDATE_POST = 'UPDATE_POST';
