
export const ADD_COMPILATIONS = 'ADD_COMPILATIONS';
export const SET_SAVE_COMPILATION_NAME = 'SET_SAVE_COMPILATION_NAME';
export const SET_POST_ID_TO_BE_SAVED = 'SET_POST_ID_TO_BE_SAVED';
export const REMOVE_COMPILATION = 'REMOVE_COMPILATION';
