
export const ADD_COMPILATIONS = 'ADD_COMPILATIONS';
export const SET_IS_SAVED_TIMEOUT = 'SET_IS_SAVED_TIMEOUT';
export const SET_POST_TO_BE_SAVED = 'SET_POST_TO_BE_SAVED';
export const SET_IS_SAVE_MODAL_OPEN = 'SET_IS_SAVE_MODAL_OPEN';
export const REMOVE_COMPILATION = 'REMOVE_COMPILATION';
