
export const SET_USER = 'SET_USER';
export const SET_FOLLOWERS = 'SET_FOLLOWERS';
export const SET_FOLLOWS = 'SET_FOLLOWS';

export const UPDATE_AVATAR = 'UPDATE_AVATAR';
export const DELETE_AVATAR = 'DELETE_AVATAR';

export const SET_PRIVATE = 'SET_PRIVATE';
export const SET_PUBLIC = 'SET_PUBLIC';

export const SET_BLACKLISTED = 'SET_BLACKLISTED';
export const SET_UNBLACKLISTED = 'SET_UNBLACKLISTED';